[package]
name = "polkadex-ido-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { version = "3.0.0", package = "parity-scale-codec", default-features = false, features = ["derive"] }
serde = { version = "1.0.68", optional = true }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
sp-rpc = {   git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19",default-features = false }
sp-blockchain = {   git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19", default-features = false }
sp-api = {   git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19", default-features = false }
sp-runtime = {   git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19", default-features = false }
pallet-polkadex-ido-primitives = {path = "../common", default-features = false}
polkadex-ido-runtime-api = {path = "runtime-api" }
polkadex-primitives = { default-features = false, branch = "gj-test-old-scale-info", git = "https://github.com/Polkadex-Substrate/polkadex-primitives.git" }
#polkadex-primitives = { git = "https://github.com/Polkadex-Substrate/polkadex-primitives.git",  branch="polkadot-v0.9.19" , default-features = false }