[dependencies.wasm-project]
default-features = false
features = []
package = 'node-template-runtime'
path = '/home/knoldus/Desktop/new-workspace/node-template/runtime'

[lib]
crate-type = ['cdylib']
name = 'node_template_runtime'

[package]
edition = '2018'
name = 'node-template-runtime-wasm'
resolver = '2'
version = '1.0.0'
[profile.dev]
panic = 'abort'

[profile.release]
lto = true
panic = 'abort'

[workspace]
