[package]
name = "engine-runtime-api"
version = "0.1.0"
authors = ["Polkadex Team"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pallet-polkadex = { default-features = false, path = "../" }
sp-api = {default-features = false, version = '2.0.0'}
sp-runtime = {default-features = false, version = '2.0.0'}
sp-arithmetic = {default-features = false, version = '2.0.0'}
sp-std = {default-features = false, version = '2.0.0'}
sp-core = {default-features = false, version = '2.0.0'}



[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
    "sp-api/std",
    'sp-core/std',
]